### ISSUE TITLE
Profile 별로 include를 다르게 하고 싶어요 

### ISSUE THREAD

**Issue by NewWisdom** [NewWisdom/TIL#65]
- 운영 DB 관련 설정 파일은 기밀정보가 담겨있기 때문에 레포에는 올리지 않고 EC2에서만 따로 가지고 있게 하고 싶었음
- [8) 스프링부트로 웹 서비스 출시하기 - 8. 운영 환경 설정](https://jojoldu.tistory.com/269) 참고해서 realdb.yml을 따로 분리
- git pull과 동기화는 어떻게 맞출거냐?
 - 이거는 프로젝트 밖에 만들면 됨
    ```json
    home/ubuntu/application/application-real-db.properties // 이런식으로
    ```
- 그런데 prod property에서 realdb property를 include하고 싶은데 애플리케이션 빌드 자체가 실패하더라
```
spring:
  profiles:
    include: realdb
  config:
    activate:
      on-profile: prod
```
- 이런식으로 작성할 경우 - run fail

![image](https://user-images.githubusercontent.com/43840561/125481347-4a386c41-5870-4c3a-a32c-1fb5d2f6ed73.png)

### **해결**

- 2.4 주요 변경사항으로 include 는 특정 profile 이 적용된 곳에서는 사용할 수 없음
- 때문에 on-profile 과 include 가 공존할 수 없음
- 2.4 에 추가된 스펙인 spring.profiles.group 속성을 사용해 문제를 해결

**application.yml**

```
spring:
  profiles:
    active: dev
    groups :
      prod : realdb
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nolto
    username: sa
    password:
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        ddl-auto: create# 한번 실행 후 추후 변경
dialect: MariaDBDialect

---
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect=org:
          hibernate:
            dialect: H2Dialect
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

```

**application-realdb.yml (분리)**

```
---
spring:
  datasource:
    url: jdbc:mariadb://우리IP:3306/nolto
    username: 비밀이지롱
    password: 비밀이지롱
    driver-class-name: org.mariadb.jdbc.Driver
  config:
    activate:
      on-profile: realdb
```

### 참고
- [spring boot 2.4 application.yaml 구동방식 변경](https://multifrontgarden.tistory.com/277)
- [8) 스프링부트로 웹 서비스 출시하기 - 8. 운영 환경 설정](https://jojoldu.tistory.com/269)
