### ISSUE TITLE
yml 실행 순서때문에 발생한 table drop

### ISSUE THREAD

**Issue by NewWisdom** [NewWisdom/TIL#67]
* 짤막한 깨달음임
* Prod 서버는 사실 아직 리빌드 하는 경우가 드물었다.
* 그러다 리빌드하고 서버를 재구동 했는데... 
* 분명 prod 환경에서는 `ddl-auto: validate`로 변경했는데, create 옵션이 먹히고 있다?
* 덕분에 데이터가 다 날아갔다. `ddl-auto: validate` 설정이 왜 묻혔을까

#### 문제의 yml 

```
spring:
  profiles:
    active: dev
    group:
      prod: realdb
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nolto
    username: sa
    password:
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
---
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        dialect=org:
          hibernate:
            dialect: H2Dialect
    show-sql: true
```

#### 이유
* yml은 작성 순서가 우선 순위의 영향을 받는다.
* Prod 환경에서는 validate 설정이 맞지만 작성 순서의 가장 마지막에서 `ddl-auto: create`를 하고 있어 덮어 씌워지게 되었다.
* yml 우선순위는 작성 순서와도 연관이 있구나...
